stages:
  - test
  - publish
image: php:7.2-cli-stretch

cache:
  paths:
    - vendor/

before_script:
  - apt-get update -yqq
  - apt-get install git unzip libzip-dev -yqq
  - docker-php-ext-install json zip
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install

services:
  - manticoresearch/manticore

unit_testing:
  stage: test
  script:
    - vendor/bin/phpunit test/
  only:
    - master

apidoc_gen:
  stage: publish
  script:
    - mkdir gh-pages
    - url_host=`git remote get-url origin | sed -e "s/https:\/\/gitlab-ci-token:.*@//g"`
    - git clone --branch=gh-pages "https://gitlab-ci-token:${WRTOK}@${url_host}" gh-pages
    - git config --global user.email "$GITLAB_USER_EMAIL"
    - git config --global user.name "$GITLAB_USER_NAME"
    - php composer.phar require apigen/apigen:dev-master  roave/better-reflection:dev-master#ce9d784
    - vendor/bin/apigen generate src --destination gh-pages
    - cd gh-pages && git add . &&  git commit -m"update apidocs" && git push
  only:
    - master
