language: php

matrix:
  include:
    - php: 7.1
      env: PHPUNIT_TEST=1
    - php: 7.3
      env: PHPUNIT_TEST=1
    - php: 7.4
      env: PHPUNIT_TEST=1
    - php: 7.4
      env: PHPUNIT_COVERAGE_TEST=1
    - php: 7.4
      env: PHPCS_TEST=1
    - php: 7.4
      env: PHPSTAN_TEST=1
    - php: 7.4
      env: PHPUNIT_TEST=1 TRANSPORT=PhpHttp
    - php: 8.0
      env: PHPUNIT_TEST=1
    - php: 8.0
      env: PHPUNIT_TEST=1 TRANSPORT=PhpHttp
services:
  -  docker

before_install:
  - docker pull manticoresearch/manticore:latest
  - docker network create manticore
  - docker run --rm --publish 9308:9308 --network manticore --name=manticoresearch-manticore --detach manticoresearch/manticore:latest
  - docker run --rm --publish 5308:9308 --network manticore --name=manticoresearch-manticore-2 --detach manticoresearch/manticore:latest
  - curl -s "http://localhost:9308/sql?mode=raw&query=show%20status%20like%20'version'"
  - curl -s "http://localhost:5308/sql?mode=raw&query=show%20status%20like%20'version'"
  - sudo apt update && sudo apt install php-json zip unzip git
env:
  global:
    - PHPSTAN_VERSION=^0.12
    - MS_HOST=127.0.0.1
    - MS_PORT=9308
    - MS_HOST2=127.0.0.1
    - MS_PORT2=5308

before_script:
  - composer validate
  - if [[ $TRANSPORT ]]; then composer require php-http/discovery php-http/curl-client guzzlehttp/psr7 php-http/message http-interop/http-factory-guzzle; fi
  - if [[ $PHPSTAN_TEST ]]; then composer require --dev phpstan/phpstan && composer require php-http/discovery php-http/curl-client guzzlehttp/psr7 php-http/message http-interop/http-factory-guzzle; fi

install:
  # See https://www.digitalocean.com/community/tutorials/how-to-remove-docker-images-containers-and-volumes
  - composer install --prefer-dist

script:
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit -d memory_limit=4G  test/; fi
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then phpdbg -qrr vendor/bin/phpunit -d memory_limit=4G --coverage-clover=coverage.xml   test/   ; fi
  - if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs --standard=PSR2 src/ test/ ; fi
  - if [[ $PHPSTAN_TEST ]]; then vendor/bin/phpstan analyse --level=3 src/; fi

after_script:
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml; fi
